In [1]:
import pandas as pd

DATASET_PATH = '../risultati/codeonly-t06.csv'
df = pd.read_csv(DATASET_PATH)

In [2]:
df.describe()

,none,c_compile,c_functional,c_almost,c_functional_subset,n
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,6.517241,5.517241,7.413793,0.206897,0.034483,19.689655
std,6.208408,6.796116,6.614471,1.114172,0.185695,1.872802
min,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000
25%,1.000000,0.000000,1.000000,0.000000,0.000000,20.000000
50%,5.000000,3.000000,7.000000,0.000000,0.000000,20.000000
75%,9.000000,8.000000,14.000000,0.000000,0.000000,20.000000
max,20.000000,20.000000,19.000000,6.000000,1.000000,21.000000

In [3]:
NONE                = 0;    NONE_KEY='none'
COMPILE_SUCCESSES   = 1;    COMPILE_KEY='c_compile'
FUNCTIONAL_SUCCESS  = 2;    FUNCTIONAL_KEY='c_functional'
ALMOST_SUCCESS      = 3;    ALMOST_KEY='c_almost'
SUBSET_SUCCESS      = 4;    SUBSET_KEY='c_functional_subset'
SCORES_KEY = 'scores'
N_KEY = 'n'

In [4]:
from utils import pass_at_k

COUNT_ALMOST_AS_FUNC = False
COUNT_SUBSET_AS_FUNC = True

compile_match   = [COMPILE_KEY]
func_match      = [FUNCTIONAL_KEY]

if COUNT_ALMOST_AS_FUNC:    func_match.append(ALMOST_KEY)
if COUNT_SUBSET_AS_FUNC:    func_match.append(SUBSET_KEY)

In [ ]:
K = 5
K_KEY = f"pass@{K}"

#df[K_KEY] = ...